name: copy_with_extension_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: ">=1.0.0 <2.0.0"

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
  copy_with_extension_gen:
    path: ../copy_with_extension_gen
  
flutter:
  uses-material-design: true
