name: copy_with_extension_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.9.0

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension:
    path: ../copy_with_extension

dev_dependencies:
  build_runner: ^1.10.3
  flutter_test:
    sdk: flutter
  copy_with_extension_gen:
    path: ../copy_with_extension_gen
    
dependency_overrides:
  copy_with_extension:
    path: ../copy_with_extension

flutter:
  uses-material-design: true
