name: copy_with_extension
version: 15.0.0
description: Annotation for generating `copyWith` extensions code using `copy_with_extension_gen`.
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension
repository: https://github.com/numen31337/copy_with_extension
issue_tracker: https://github.com/numen31337/copy_with_extension/issues
topics:
  - copy-with
  - code-generation
  - build-runner
  - immutability
  - codegen

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: '>=5.0.0 <7.0.0'
