targets:
  $default:
    builders:
      copy_with_extension_gen:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  copy_with_extension_gen:
    target: ":copy_with_extension_gen"
    import: "package:copy_with_extension_gen/builder.dart"
    builder_factories: ["copyWith"]
    build_extensions: {".dart": ["copy_with_extension_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]